# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Contacts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Contacts
  pod 'RxSwift', '4.2.0'
  pod 'RxCocoa', '4.2.0'

  target 'ContactsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest', '4.2.0'
    pod 'iOSSnapshotTestCase'
  end

  target 'ContactsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
